### ISSUE TITLE
Missing file Classes.gdf

### ISSUE THREAD

**Issue by bayganik** [htmlcoderexe/3DGame#1]
the missing classes.gdf stops the game from playing.  What is suppose to be in that class?  I tried a view versions and could not get the program to accept it.

**Comment by htmlcoderexe** [comment]
Okay, so this is a case of "works on my system" since I didn't think too much about how it would work outside of it (I already burned myself earlier on the project using textures that weren't pulled in by git).

So the way it works now is that there's a class with functions to read/write one of these files (some basic documentation on the wiki), which currently defaults to [exe dir]\gamedata\[filename.gdf]. The files I currently have in there now are in the 3Dgame output dir, "unofficially", and the MagicEditor exe file (which can edit/view these and also creates dummy blanks in case it doesn't find them) is also in there - so whenever I run it on my system from that dir, it sees/creates these files and the game exe can also use them.

I don't have the time right now, what with the coming holidays, but here's roughly what I need to do to fix it, roughly in order:

1. include some basic versions of these files in the game data that's on here - I am going to have some available but right now it's like 1 test class with some abilities that don't do much - but at least the game will run. 
2. put some error handling into the game itself - maybe load some kind of a dummy in case the files are missing

3. kludge something together (maybe some build actions in visual studio?) to make sure that the editor creates/edits files that belong with the game (maybe some sort of a registry / config thing?) - this will need some messing around

**Comment by htmlcoderexe** [comment]
I added the necessary files and updated the project file to automatically throw them into the bin folder of the compiled game.

To modify the files in-project, the MagicEditor exe must be placed in the 3DGame folder - any edits to these files will then be used when compiling the game. It is also possible to edit the files after compilation, this is the intended use when not doing development (for "modding" and such). This is not recommended when you work with the source code because any changes to the "original" files will overwrite your modifications made to the files with the compiled game.
